### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by skeept** [molok/vim-smartusline#7]
I have tried to use this plugin but I can't seem to make it work

In the end of my vimrc I have the lines:
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
let g:smartusline_string_to_highlight = '(%n) %f '

but I can't see any part of the statusline highlighted.
Is there anything I am missing?

**Comment by molok** [comment]
smartusline_string_to_highlight should be a substring of your statusline, so you could either change your statusline to
set statusline=%<(%n) %f\ %h%m%r%=%-14.(%l,%c%V%)\ %P 

or smartusline_string_to_highlight to

let g:smartusline_string_to_highlight = '%f '

**Comment by skeept** [comment]
Thanks now I understand how to  configure it!
